name: Code Review and Pull Request

on:
  push:
    branches:
      - 'feature/*'  # Déclenche le workflow pour les branches nommées 'feature/*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create pull request
      id: create_pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.TOKEN_GITHUB }}
        commit-message: "Add new feature"
        branch: ${{ github.ref }}
        base: main  # Remplacer par la branche principale de votre dépôt si différente
        title: "New feature from ${{ github.ref }}"
        body: "This PR adds a new feature."

    - name: Set PR number
      run: echo "PR_NUMBER=${{ steps.create_pr.outputs.pull-request-number }}" >> $GITHUB_ENV

  run_code_review:
    runs-on: ubuntu-latest
    needs: create_pull_request
    steps:
    - name: Wait for pull request creation
      run: sleep 20

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set repository details
      run: |
        echo "GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "GITHUB_REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

    - name: Run code review script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        PR_NUMBER: ${{ env.PR_NUMBER }}
        GITHUB_REPOSITORY_OWNER: ${{ env.GITHUB_REPOSITORY_OWNER }}
        GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
      run: python review_code.py

  run_tests:
    runs-on: ubuntu-latest
    needs: run_code_review
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s calculator/tests
