name: Code Review and Pull Request

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'mezzache.pro@gmail.com'

    - name: Create pull request
      id: create_pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.TOKEN_GITHUB }}
        commit-message: "Add new feature"
        branch: ${{ github.ref }}
        base: main 
        title: "New feature from ${{ github.ref }}"
        body: "This PR adds a new feature."

     - name: Save PR number to file
      run: echo "${{ steps.create_pr.outputs.pull-request-number }}" > pr_number.txt

    - name: Upload PR number artifact
      uses: actions/upload-artifact@v2
      with:
        name: pr_number
        path: pr_number.txt

  run_code_review:
    runs-on: ubuntu-latest
    needs: create_pull_request
    steps:
    - name: Wait for pull request creation
      run: sleep 20

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download PR number artifact
      uses: actions/download-artifact@v2
      with:
        name: pr_number

    - name: Retrieve PR number from file
      run: PR_NUMBER=$(cat pr_number.txt) && echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

    - name: Set repository details
      run: |
        echo "GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "GITHUB_REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

    - name: Run code review script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        PR_NUMBER: ${{ env.PR_NUMBER }}
        GITHUB_REPOSITORY_OWNER: ${{ env.GITHUB_REPOSITORY_OWNER }}
        GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
      run: python review_code.py

  run_tests:
    runs-on: ubuntu-latest
    needs: run_code_review
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s calculator/tests
