name: Code Review and Pull Request

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create pull request
      id: create_pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.TOKEN_GITHUB }}
        commit-message: "Add new feature"
        branch: ${{ github.ref }}
        base: main 
        title: "New feature from ${{ github.ref }}"
        body: "This PR adds a new feature."

  run_code_review:
    runs-on: ubuntu-latest
    needs: create_pull_request
    steps:
    - name: Wait for pull request creation
      run: sleep 20

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code review script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python review_code.py

  run_tests:
    runs-on: ubuntu-latest
    needs: run_code_review
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s calculator/tests
